### ISSUE TITLE
QUT Virtual is now HiQ

### ISSUE THREAD

**Issue by LowRentTrent** [matt-downs/QUT-Linker#1]
QUT Virtual is now HiQ so the name of the link needs to be changed, cosmetic change only. Should be one link for everything. https://qutvirtual4.qut.edu.au

Assignment minder doesn't seem to exist anymore? Refer: https://blogs.qut.edu.au/library/tag/assignment-minder/

These would be my suggested additions for 2018
- https://qutvirtual4.qut.edu.au/group/student/calendar
- https://spaces.library.qut.edu.au/

Thanks!

**Comment by matt-downs** [comment]
Sweet!! Thanks for the info!

**Comment by matt-downs** [comment]
Doneski 😄

**Comment by LowRentTrent** [comment]
Everything is perfect - you are an absolute star. Thankyou Matt!
